FROM nginx:alpine

# COPY ./app/html /usr/share/nginx/html
# COPY ./app/css /usr/share/nginx/html/css
# COPY ./app/javascript /usr/share/nginx/html/javascript
# COPY ./app/img /usr/share/nginx/html/img

#COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]